server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: ${SPRING_CONFIG_IMPORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"